
# Basic VAE uses one-hot encoded values of protein sequences
basic_vae:
# Experiments to see how the latent dimension affects the reconstruction
  latent_exp:
    exp_1:
      model: BasicVAE_exp_1
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      dropout: 0.4
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 64
      hidden_dims: 512
      seed: 42
      beta: 1 
      max_seq_len: 500

    exp_2:
      model: BasicVAE_exp_2
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      dropout: 0.4
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 32
      hidden_dims: 512
      seed: 42
      beta: 1
      max_seq_len: 500

    exp_3:
      model: BasicVAE_exp_3
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      dropout: 0.1
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 128
      hidden_dims: 1024
      seed: 42
      beta: 1
      max_seq_len: 500

    exp_4:
      model: BasicVAE_exp_4
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      dropout: 0.4
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 8
      hidden_dims: 512
      seed: 42
      beta: 1
      max_seq_len: 500

    # exp_5:
    #   model: BasicVAE_exp_5
    #   dataset: 'GO'
    #   data_type: 'point'
    #   batch_size: 256
    #   epochs: 200
    #   optimizer: adamw
    #   optimizer_param:
    #       lr: 0.001
    #   latent_dim: 32
    #   hidden_dims: 1024
    #   seed: 42
    #   max_seq_len: 500

AttentionVAE:
  latent_exp:
    exp_1:
      model: AttentionVAE_exp_1
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 64
      embed_dim: 128
      hidden_dim: 256
      num_heads: 4
      dropout: 0.4
      seed: 42
      max_seq_len: 500

    exp_2:
      model: AttentionVAE_exp_2
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 32
      embed_dim: 128
      hidden_dim: 256
      num_heads: 4
      dropout: 0.4
      seed: 42
      max_seq_len: 500

    exp_3:
      model: AttentionVAE_exp_3
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 16
      embed_dim: 128
      hidden_dim: 256
      num_heads: 4
      dropout: 0.4
      seed: 42
      max_seq_len: 500

    exp_4:
      model: AttentionVAE_exp_4
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 8
      embed_dim: 128
      hidden_dim: 256
      num_heads: 4
      dropout: 0.4
      seed: 42
      max_seq_len: 500

PointNetVAE:

GraphVAE:
  

