
# Basic VAE uses one-hot encoded values of protein sequences
basic_vae:
# Experiments to see how the latent dimension affects the reconstruction
  latent_exp:
    exp_1:
      model: BasicVAE_exp_1
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 256
      hidden_dims: 1024
      seed: 42
      max_seq_len: 2046

    exp_2:
      model: BasicVAE_exp_2
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 128
      hidden_dims: 1024
      seed: 42
      max_seq_len: 2046

    exp_3:
      model: BasicVAE_exp_3
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 64
      hidden_dims: 1024
      seed: 42
      max_seq_len: 2046

    exp_4:
      model: BasicVAE_exp_4
      dataset: 'GO'
      data_type: 'point'
      batch_size: 256
      epochs: 200
      optimizer: adamw
      optimizer_param:
          lr: 0.001
      latent_dim: 2
      hidden_dims: 1024
      seed: 42
      max_seq_len: 500

PointNetVAE:

GraphVAE:
  

